server:
  port: 8080

spring:
  application:
    name: blur-auth
    
#스웨거 설정  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://blurblur.kr:3306/blur_auth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: blur
#    password: blurblur
    url: jdbc:mysql://127.0.0.1:3306/blur?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  #redis 설정
#  redis:
#    host: blurblur.kr
#    port: 6379
#    username: blur
#    password: blurblur

  redis:
    host: 127.0.0.1
    port: 6379

  # JPA 설정
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  logging.level:
    #    org.hibernate.SQL: debug
    #    org.hibernate.type: trace
    #    org.springframework.security: DEBUG
    #    org.springframework.security.oauth2: TRACE
    org.hibernate.SQL: error
    org.hibernate.type: error
    org.springframework.security: error
    org.springframework.security.oauth2: error

  # Security OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2820dd0f9d4da11c57a25ab3f29de16c
            client-secret: cXiw9put8fVqQ0rW436JqzJIdtSyRDWp
#            redirect-uri: http://blurblur.kr/api/login/oauth2/code/kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


mail:
  host: smtp.gmail.com
  port: 465
  protocol: smtp
  username: blurb307@gmail.com
  password: tmvrjqvfxwwshppf
  debug: true
  smtp:
    auth: true
    starttls-tls-enable: true
    ssl:
      trust: smtp.gmail.com
      enable: true

jwt:
  secretKey: SN5OUPJANIZLB/hZ1q7CsJbHvvuZ5xahm6DZMxTZyDI=

  access:
    expiration: 1800000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h)) 밀리초
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?)) 밀리초

cookie:
  access:
    expiration: 1800 # 초

  refresh:
    expiration: 1209600 # 초

      

