server:
  port: 8081

spring:
  application:
    name: blur-user

  #스웨거 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://blurblur.kr:3307/blur_user?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: blur
#    password: blurblur
    url: jdbc:mysql://127.0.0.1:3306/blur?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: alcls1743!@

#  redis:
#    host: blurblur.kr
#    port: 6379
#    username: blur
#    password: blurblur

  redis:
    host: 127.0.0.1
    port: 6379

  # JPA 설정
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

cloud:
  aws:
    credentials:
      accessKey: AKIAXM2ROBDTA7R7L6M4      # AWS IAM AccessKey 적기
      secretKey: 9RJ1UENpMmk6c/3DZmPV2YQoZhOvTWSgAXh5JOOo   # AWS IAM SecretKey 적기
    s3:
      bucket: blur307bucket    # ex) marryting-gyunny
      dir: /blur # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false

blur-auth:
  url: https://blurblur.kr/blur-auth/user